from __future__ import annotations
import attrs
import logging
import numpy as np
import os
import typing as tp
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from NaviNIBS.Navigator.Model.Session import Session
from NaviNIBS.Navigator.Model.HeadModel import MshVersion

from NaviNIBS.Navigator.Model.CoordinateSystems.CoordinateSystem import CoordinateSystem
from NaviNIBS.Navigator.Model.GenericCollection import GenericCollection, GenericCollectionDictItem

logger = logging.getLogger(__name__)


@attrs.define
class CoordinateSystems(GenericCollection[str, CoordinateSystem]):
    _session: tp.Optional[Session] = attrs.field(default=None, repr=False)

    def __attrs_post_init__(self):
        super().__attrs_post_init__()

        if self.session is not None:
            self.session.headModel.sigFilepathChanged.connect(self.autogenerateCoordinateSystems)
            self.autogenerateCoordinateSystems()

    @property
    def session(self):
        return self._session

    @session.setter
    def session(self, newSes: tp.Optional[Session]):
        if self._session is newSes:
            return
        if self._session is not None:
            self.session.headModel.sigFilepathChanged.disconnect(self.autogenerateCoordinateSystems)
        self.setAttribForItems(self.keys(), dict(session=[newSes for key in self.keys()]))
        self._session = newSes
        if newSes is not None:
            newSes.headModel.sigFilepathChanged.connect(self.autogenerateCoordinateSystems)
        self.autogenerateCoordinateSystems()

    def autogenerateCoordinateSystems(self):
        if self.session is not None:
            if self.session.headModel.filepath is not None:
                # autogenerate from files generated by SimNIBS
                logger.info('Autogenerating coord system transforms from SimNIBS results')

                m2mDir = self.session.headModel.m2mDir

                inputPath = os.path.join(m2mDir, 'toMNI', 'MNI2conform_12DOF.txt')
                if os.path.exists(inputPath):
                    with open(inputPath, 'r') as f:
                        MNIToMRITransf = np.loadtxt(f)

                    from NaviNIBS.Navigator.Model.CoordinateSystems.Affine import AffineTransformedCoordinateSystem

                    coordSys = AffineTransformedCoordinateSystem(
                        key='MNI_SimNIBS12DoF',
                        description='SimNIBS-generated 12DoF MNI transform',
                        transfThisToWorld=MNIToMRITransf,
                        isAutogenerated=True
                    )
                    if coordSys.key in self._items:
                        assert self._items[coordSys.key].isAutogenerated
                    self.setItem(coordSys)
                else:
                    if self.session.headModel.mshVersion == MshVersion.HEADRECO:
                        logger.error(f'Did not find expected input file at {inputPath}')
                    else:
                        logger.info(f'No SimNIBS-generated 12DoF MNI transform found at {inputPath}, ')

                if True:
                    # prefer .nii.gz, fall back to .nii for both MNI2Conform and Conform2MNI
                    base_toConform = os.path.join(m2mDir, 'toMNI', 'MNI2Conform_nonl')
                    candidates_toConform = [base_toConform + ext for ext in ('.nii.gz', '.nii')]
                    inputPath_toConform = next((p for p in candidates_toConform if os.path.exists(p)), None)

                    base_toMNI = os.path.join(m2mDir, 'toMNI', 'Conform2MNI_nonl')
                    candidates_toMNI = [base_toMNI + ext for ext in ('.nii.gz', '.nii')]
                    inputPath_toMNI = next((p for p in candidates_toMNI if os.path.exists(p)), None)

                    if inputPath_toConform is not None and inputPath_toMNI is not None:
                        from NaviNIBS.Navigator.Model.CoordinateSystems.Nonlinear import NonlinearTransformedCoordinateSystem

                        coordSys = NonlinearTransformedCoordinateSystem(
                            key='MNI_SimNIBSNonlinear',
                            description='SimNIBS-generated nonlinear MNI transform',
                            deformationFieldThisToWorld_filepath=inputPath_toConform,
                            deformationFieldWorldToThis_filepath=inputPath_toMNI,
                            isAutogenerated=True
                        )
                        if coordSys.key in self._items:
                            assert self._items[coordSys.key].isAutogenerated
                        self.setItem(coordSys)
                    else:
                        if inputPath_toConform is None:
                            logger.error(f'Did not find expected input file for MNI2Conform_nonl at any of: {candidates_toConform}')
                        if inputPath_toMNI is None:
                            logger.error(f'Did not find expected input file for Conform2MNI_nonl at any of: {candidates_toMNI}')

            if self.session.headModel.freesurferFilepath is not None:
                logger.info('Autogenerating coord system transforms from FreeSurfer SynthMorph results')
                warpSubpath = os.path.join('mri', 'transforms', 'synthmorph.1.0mm.1.0mm',
                                           'warp.to.mni152.1.0mm.1.0mm.nii.gz')
                warpInvSubpath = os.path.join('mri', 'transforms', 'synthmorph.1.0mm.1.0mm',
                                              'warp.to.mni152.1.0mm.1.0mm.inv.nii.gz')
                inputPath_toMNI = self.session.headModel.getFreesurferSubfilePath(warpInvSubpath)
                inputPath_toConform = self.session.headModel.getFreesurferSubfilePath(warpSubpath)

                if inputPath_toMNI and os.path.exists(inputPath_toMNI) \
                        and inputPath_toConform and os.path.exists(inputPath_toConform):

                    from NaviNIBS.Navigator.Model.CoordinateSystems.Nonlinear import NonlinearTransformedCoordinateSystem

                    coordSys = NonlinearTransformedCoordinateSystem(
                        key='MNI_SynthMorphNonlinear',
                        description='FreeSurfer SynthMorph nonlinear MNI transform',
                        deformationFieldThisToWorld_filepath=inputPath_toConform,
                        deformationFieldWorldToThis_filepath=inputPath_toMNI,
                        isAutogenerated=True,
                        isDeltas=True,
                    )
                    if coordSys.key in self._items:
                        assert self._items[coordSys.key].isAutogenerated
                    self.setItem(coordSys)
                else:
                    if not (inputPath_toMNI and os.path.exists(inputPath_toMNI)):
                        logger.error(f'Did not find SynthMorph warp at subpath: {warpSubpath}')
                    if not (inputPath_toConform and os.path.exists(inputPath_toConform)):
                        logger.error(f'Did not find SynthMorph inverse warp at subpath: {warpInvSubpath}')


    def asList(self) -> list[dict[str, tp.Any]]:
        # (don't include auto-generated coord systems since they can be restored separately)
        return [coordSys.asDict() for coordSys in self._items.values() if not coordSys.isAutogenerated]

    @classmethod
    def fromList(cls, coordSysList: list[dict[str, tp.Any]]) -> CoordinateSystems:
        coordinateSystems = {}
        for coordSysDict in coordSysList:
            match coordSysDict['__type']:
                case 'AffineTransformedCoordinateSystem':
                    from NaviNIBS.Navigator.Model.CoordinateSystems.Affine import AffineTransformedCoordinateSystem
                    CoordSysCls = AffineTransformedCoordinateSystem
                case 'NonlinearTransformedCoordinateSystem':
                    from NaviNIBS.Navigator.Model.CoordinateSystems.Nonlinear import NonlinearTransformedCoordinateSystem
                    CoordSysCls = NonlinearTransformedCoordinateSystem
                case _:
                    raise NotImplementedError("Unexpected CoordinateSystem type: {coordSysDict['__type']}")

            coordinateSystems[coordSysDict['key']] = CoordSysCls.fromDict(coordSysDict)

        return cls(items=coordinateSystems)
