from __future__ import annotations
import attrs
import logging
import numpy as np
import os
import typing as tp
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from NaviNIBS.Navigator.Model.Session import Session
from NaviNIBS.Navigator.Model.HeadModel import MshVersion

from NaviNIBS.Navigator.Model.CoordinateSystems.CoordinateSystem import CoordinateSystem
from NaviNIBS.Navigator.Model.CoordinateSystems.Placeholder import PlaceholderCoordinateSystem
from NaviNIBS.Navigator.Model.GenericCollection import GenericCollection, GenericCollectionDictItem

logger = logging.getLogger(__name__)


@attrs.define
class CoordinateSystems(GenericCollection[str, CoordinateSystem]):
    _session: tp.Optional[Session] = attrs.field(default=None, repr=False)

    def __attrs_post_init__(self):
        super().__attrs_post_init__()

        if self.session is not None:
            self.session.headModel.sigFilepathChanged.connect(self.autogenerateCoordinateSystems)
            self.autogenerateCoordinateSystems()

    @property
    def session(self):
        return self._session

    @session.setter
    def session(self, newSes: tp.Optional[Session]):
        if self._session is newSes:
            return
        if self._session is not None:
            self.session.headModel.sigFilepathChanged.disconnect(self.autogenerateCoordinateSystems)
        self.setAttribForItems(self.keys(), dict(session=[newSes for key in self.keys()]))
        self._session = newSes
        if newSes is not None:
            newSes.headModel.sigFilepathChanged.connect(self.autogenerateCoordinateSystems)
        self.autogenerateCoordinateSystems()

    def _existingKwargsFor(self, key: str) -> dict:
        """
        Returns kwargs to merge into a freshly autogenerated coord system at ``key``,
        preserving any user-tunable state already attached to the item at that key:
          - If a PlaceholderCoordinateSystem (loaded from a saved session before
            autogeneration ran), use its persisted kwargs.
          - If a previously-autogenerated real instance (e.g. autogeneration is
            re-running because the head model path changed), preserve the same
            user-tunable fields directly off the live instance.
        Asserts that any non-placeholder existing item is itself autogenerated,
        preserving the original invariant.
        """
        existing = self._items.get(key)
        if existing is None:
            return {}
        if isinstance(existing, PlaceholderCoordinateSystem):
            return existing.getPersistedKwargs()
        assert existing.isAutogenerated
        return dict(isVisible=existing.isVisible)

    def autogenerateCoordinateSystems(self):
        if self.session is not None:
            if self.session.headModel.filepath is not None:
                # autogenerate from files generated by SimNIBS
                logger.info('Autogenerating coord system transforms from SimNIBS results')

                m2mDir = self.session.headModel.m2mDir

                inputPath = os.path.join(m2mDir, 'toMNI', 'MNI2conform_12DOF.txt')
                if os.path.exists(inputPath):
                    with open(inputPath, 'r') as f:
                        MNIToMRITransf = np.loadtxt(f)

                    from NaviNIBS.Navigator.Model.CoordinateSystems.Affine import AffineTransformedCoordinateSystem

                    key = 'MNI_SimNIBS12DoF'
                    coordSys = AffineTransformedCoordinateSystem(
                        key=key,
                        description='SimNIBS-generated 12DoF MNI transform',
                        transfThisToWorld=MNIToMRITransf,
                        isAutogenerated=True,
                        **self._existingKwargsFor(key),
                    )
                    self.setItem(coordSys)
                else:
                    if self.session.headModel.mshVersion == MshVersion.HEADRECO:
                        logger.error(f'Did not find expected input file at {inputPath}')
                    else:
                        logger.info(f'No SimNIBS-generated 12DoF MNI transform found at {inputPath}, ')

                if True:
                    # prefer .nii.gz, fall back to .nii for both MNI2Conform and Conform2MNI
                    base_toConform = os.path.join(m2mDir, 'toMNI', 'MNI2Conform_nonl')
                    candidates_toConform = [base_toConform + ext for ext in ('.nii.gz', '.nii')]
                    inputPath_toConform = next((p for p in candidates_toConform if os.path.exists(p)), None)

                    base_toMNI = os.path.join(m2mDir, 'toMNI', 'Conform2MNI_nonl')
                    candidates_toMNI = [base_toMNI + ext for ext in ('.nii.gz', '.nii')]
                    inputPath_toMNI = next((p for p in candidates_toMNI if os.path.exists(p)), None)

                    if inputPath_toConform is not None and inputPath_toMNI is not None:
                        from NaviNIBS.Navigator.Model.CoordinateSystems.Nonlinear import NonlinearTransformedCoordinateSystem

                        key = 'MNI_SimNIBSNonlinear'
                        coordSys = NonlinearTransformedCoordinateSystem(
                            key=key,
                            description='SimNIBS-generated nonlinear MNI transform',
                            deformationFieldThisToWorld_filepath=inputPath_toConform,
                            deformationFieldWorldToThis_filepath=inputPath_toMNI,
                            isAutogenerated=True,
                            **self._existingKwargsFor(key),
                        )
                        self.setItem(coordSys)
                    else:
                        if inputPath_toConform is None:
                            logger.error(f'Did not find expected input file for MNI2Conform_nonl at any of: {candidates_toConform}')
                        if inputPath_toMNI is None:
                            logger.error(f'Did not find expected input file for Conform2MNI_nonl at any of: {candidates_toMNI}')

                if self.session.headModel.mshVersion == MshVersion.CHARM:
                    # autogenerate SBM (fsaverage) mapping from CHARM surfaces
                    surfDir = os.path.join(m2mDir, 'surfaces')
                    lhPial = os.path.join(surfDir, 'lh.pial.gii')
                    rhPial = os.path.join(surfDir, 'rh.pial.gii')
                    lhSphereReg = os.path.join(surfDir, 'lh.sphere.reg.gii')
                    rhSphereReg = os.path.join(surfDir, 'rh.sphere.reg.gii')

                    sbmInputs = (lhPial, rhPial, lhSphereReg, rhSphereReg)
                    if all(os.path.exists(p) for p in sbmInputs):
                        from NaviNIBS.Navigator.Model.CoordinateSystems.SBM import SBMTransformedCoordinateSystem

                        key = 'FSAvg_SimNIBS_SBM'
                        coordSys = SBMTransformedCoordinateSystem(
                            key=key,
                            description='SBM (fsaverage) mapping via SimNIBS/CHARM surfaces',
                            nativePial_filepaths=(lhPial, rhPial),
                            nativeSphere_filepaths=(lhSphereReg, rhSphereReg),
                            isAutogenerated=True,
                            **self._existingKwargsFor(key),
                        )
                        self.setItem(coordSys)
                    else:
                        for p in sbmInputs:
                            if not os.path.exists(p):
                                logger.error(f'Did not find expected SBM input file at {p}')

            if self.session.headModel.freesurferFilepath is not None:
                logger.info('Autogenerating coord system transforms from FreeSurfer SynthMorph results')
                warpSubpath = os.path.join('mri', 'transforms', 'synthmorph.1.0mm.1.0mm',
                                           'warp.to.mni152.1.0mm.1.0mm.nii.gz')
                warpInvSubpath = os.path.join('mri', 'transforms', 'synthmorph.1.0mm.1.0mm',
                                              'warp.to.mni152.1.0mm.1.0mm.inv.nii.gz')
                inputPath_toMNI = self.session.headModel.getFreesurferSubfilePath(warpInvSubpath)
                inputPath_toConform = self.session.headModel.getFreesurferSubfilePath(warpSubpath)

                if inputPath_toMNI and os.path.exists(inputPath_toMNI) \
                        and inputPath_toConform and os.path.exists(inputPath_toConform):

                    from NaviNIBS.Navigator.Model.CoordinateSystems.Nonlinear import NonlinearTransformedCoordinateSystem

                    key = 'MNI_SynthMorphNonlinear'
                    coordSys = NonlinearTransformedCoordinateSystem(
                        key=key,
                        description='FreeSurfer SynthMorph nonlinear MNI transform',
                        deformationFieldThisToWorld_filepath=inputPath_toConform,
                        deformationFieldWorldToThis_filepath=inputPath_toMNI,
                        isAutogenerated=True,
                        isDeltas=True,
                        **self._existingKwargsFor(key),
                    )
                    self.setItem(coordSys)
                else:
                    if not (inputPath_toMNI and os.path.exists(inputPath_toMNI)):
                        logger.error(f'Did not find SynthMorph warp at subpath: {warpSubpath}')
                    if not (inputPath_toConform and os.path.exists(inputPath_toConform)):
                        logger.error(f'Did not find SynthMorph inverse warp at subpath: {warpInvSubpath}')

                # autogenerate SBM (fsaverage) mapping from FreeSurfer surfaces
                fsSurfSubpaths = {
                    'lhPial': os.path.join('surf', 'lh.pial.T1'),
                    'rhPial': os.path.join('surf', 'rh.pial.T1'),
                    'lhSphereReg': os.path.join('surf', 'lh.sphere.reg'),
                    'rhSphereReg': os.path.join('surf', 'rh.sphere.reg'),
                }
                fsSurfPaths = {
                    key: self.session.headModel.getFreesurferSubfilePath(subpath)
                    for key, subpath in fsSurfSubpaths.items()
                }
                if all(p is not None and os.path.exists(p) for p in fsSurfPaths.values()):
                    from NaviNIBS.Navigator.Model.CoordinateSystems.SBM import SBMTransformedCoordinateSystem

                    key = 'FSAvg_FreeSurfer_SBM'
                    coordSys = SBMTransformedCoordinateSystem(
                        key=key,
                        description='SBM (fsaverage) mapping via FreeSurfer surfaces',
                        nativePial_filepaths=(fsSurfPaths['lhPial'], fsSurfPaths['rhPial']),
                        nativeSphere_filepaths=(fsSurfPaths['lhSphereReg'], fsSurfPaths['rhSphereReg']),
                        isAutogenerated=True,
                        **self._existingKwargsFor(key),
                    )
                    self.setItem(coordSys)
                else:
                    for key, subpath in fsSurfSubpaths.items():
                        p = fsSurfPaths[key]
                        if p is None or not os.path.exists(p):
                            logger.error(f'Did not find FreeSurfer SBM input file at subpath: {subpath}')


    def asList(self) -> list[dict[str, tp.Any]]:
        # Autogenerated systems would be re-created from the head model on load, so we
        # don't persist their full state — but we do persist a placeholder carrying
        # the user-tunable bits (currently just isVisible) so those survive a round-trip.
        out: list[dict[str, tp.Any]] = []
        for coordSys in self._items.values():
            if coordSys.isAutogenerated:
                coordSys = PlaceholderCoordinateSystem(
                    key=coordSys.key,
                    isVisible=coordSys.isVisible,
                )

            if isinstance(coordSys, PlaceholderCoordinateSystem):
                d = coordSys.asDict()
                if not any(k in d for k in coordSys.getPersistedKwargs().keys()):
                    # don't write anything for placeholders that have no non-default kwargs
                    continue
                else:
                    out.append(coordSys.asDict())
            else:
                out.append(coordSys.asDict())
        return out

    @classmethod
    def fromList(cls, coordSysList: list[dict[str, tp.Any]]) -> CoordinateSystems:
        coordinateSystems = {}
        for coordSysDict in coordSysList:
            coordSysDict = dict(coordSysDict)  # local copy so we can pop __type
            typeName = coordSysDict.pop('__type')
            match typeName:
                case 'AffineTransformedCoordinateSystem':
                    from NaviNIBS.Navigator.Model.CoordinateSystems.Affine import AffineTransformedCoordinateSystem
                    CoordSysCls = AffineTransformedCoordinateSystem
                case 'NonlinearTransformedCoordinateSystem':
                    from NaviNIBS.Navigator.Model.CoordinateSystems.Nonlinear import NonlinearTransformedCoordinateSystem
                    CoordSysCls = NonlinearTransformedCoordinateSystem
                case 'SBMTransformedCoordinateSystem':
                    from NaviNIBS.Navigator.Model.CoordinateSystems.SBM import SBMTransformedCoordinateSystem
                    CoordSysCls = SBMTransformedCoordinateSystem
                case 'PlaceholderCoordinateSystem':
                    CoordSysCls = PlaceholderCoordinateSystem
                case _:
                    raise NotImplementedError(f"Unexpected CoordinateSystem type: {typeName!r}")

            coordinateSystems[coordSysDict['key']] = CoordSysCls.fromDict(coordSysDict)

        return cls(items=coordinateSystems)
