from __future__ import annotations
import attrs
import logging
import numpy as np

from NaviNIBS.Navigator.Model.CoordinateSystems.CoordinateSystem import CoordinateSystem

logger = logging.getLogger(__name__)


@attrs.define(kw_only=True)
class PlaceholderCoordinateSystem(CoordinateSystem):
    """
    Lightweight stand-in for an autogenerated coord system, used only across
    save/load: ``CoordinateSystems.asList`` emits one of these per autogenerated
    item to preserve user-tunable state (currently just ``isVisible``), and
    ``autogenerateCoordinateSystems`` consumes its kwargs when materializing
    the real system. Holds no transform machinery.
    """

    _isVisible: bool = False

    def transformFromWorldToThis(self, coords: np.ndarray) -> np.ndarray:
        raise RuntimeError(
            f'PlaceholderCoordinateSystem {self._key!r} cannot transform; '
            f'autogeneration has not yet replaced it.'
        )

    def transformFromThisToWorld(self, coords: np.ndarray) -> np.ndarray:
        raise RuntimeError(
            f'PlaceholderCoordinateSystem {self._key!r} cannot transform; '
            f'autogeneration has not yet replaced it.'
        )

    def getPersistedKwargs(self) -> dict:
        return dict(isVisible=self._isVisible)
