from __future__ import annotations

import inspect
import logging
import typing as tp

from qtpy import QtCore, QtWidgets

if tp.TYPE_CHECKING:
    from NaviNIBS.Navigator.Model.Session import Session
from NaviNIBS.Navigator.Model.CoordinateSystems.Placeholder import PlaceholderCoordinateSystem

logger = logging.getLogger(__name__)


class EditCoordinateSystemVisibilityDialog(QtWidgets.QDialog):
    """
    Small modal dialog letting the user pick which of the session's coordinate systems
    are shown in the coordinate widgets. Applies on OK by setting ``isVisible`` on each
    coord system (which fires ``sigItemChanged`` and prompts the widgets to redraw).
    """

    def __init__(self, session: Session, parent: QtWidgets.QWidget | None = None):
        super().__init__(parent)
        self._session = session
        self._checkBoxesByKey: dict[str, QtWidgets.QCheckBox] = {}

        self.setWindowTitle('Edit visible coordinate systems')
        self.setModal(True)

        layout = QtWidgets.QVBoxLayout()
        self.setLayout(layout)

        helpLabel = QtWidgets.QLabel(inspect.cleandoc("""
                Choose which coordinate systems to display alongside World coordinates.
                                                                                 
                Some systems (e.g., nonlinear MNI, surface-based morphometry) may take several seconds to initialize.
            """
        ))
        helpLabel.setWordWrap(True)
        layout.addWidget(helpLabel)

        formContainer = QtWidgets.QWidget()
        formLayout = QtWidgets.QFormLayout()
        formLayout.setContentsMargins(0, 0, 0, 0)
        formContainer.setLayout(formLayout)
        layout.addWidget(formContainer)

        for key, cs in self._session.coordinateSystems.items():
            if isinstance(cs, PlaceholderCoordinateSystem):
                # Placeholders correspond to autogenerated systems whose head-model
                # inputs are not currently available. Skip them — they can't be displayed
                # even if toggled on, so showing them in the dialog would be misleading.
                continue
            checkBox = QtWidgets.QCheckBox()
            checkBox.setChecked(cs.isVisible)
            if cs.description:
                checkBox.setToolTip(cs.description)
            formLayout.addRow(key, checkBox)
            self._checkBoxesByKey[key] = checkBox

        if not self._checkBoxesByKey:
            emptyLabel = QtWidgets.QLabel('(No coordinate systems available in this session.)')
            emptyLabel.setStyleSheet('font-style: italic;')
            formLayout.addRow(emptyLabel)

        buttonBox = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Cancel
        )
        buttonBox.accepted.connect(self._onAccepted)
        buttonBox.rejected.connect(self.reject)
        layout.addWidget(buttonBox)

    def _onAccepted(self):
        for key, checkBox in self._checkBoxesByKey.items():
            cs = self._session.coordinateSystems[key]
            cs.isVisible = checkBox.isChecked()
        self.accept()
